// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int? NumButaca { get; set; }

    public string FilaButaca { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual ICollection<SalaButaca> SalaButacas { get; set; } = new List<SalaButaca>();
}