// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Categoria
{
    public int IdCategoria { get; set; }

    public string Categoria1 { get; set; }

    public virtual ICollection<Consumible> Consumibles { get; set; } = new List<Consumible>();
}