// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Clasificacion
{
    public int IdClasificacion { get; set; }

    public string Clasificacion1 { get; set; }

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();
}