// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string NomCliente { get; set; }

    public string ApeCliente { get; set; }

    public int IdTipoCliente { get; set; }

    public int IdBarrio { get; set; }

    public int IdContacto { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Contacto IdContactoNavigation { get; set; }

    public virtual TiposCliente IdTipoClienteNavigation { get; set; }
}