// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Combo
{
    public int IdCombo { get; set; }

    public string NomCombo { get; set; }

    public virtual ICollection<DetallesCombo> DetallesCombos { get; set; } = new List<DetallesCombo>();

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
}