// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Consumible
{
    public int IdConsumible { get; set; }

    public int IdCategoria { get; set; }

    public string NomConsumible { get; set; }

    public int IdMarca { get; set; }

    public int? PreUnitario { get; set; }

    public virtual ICollection<DetallesCombo> DetallesCombos { get; set; } = new List<DetallesCombo>();

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual Marca IdMarcaNavigation { get; set; }
}