// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class DetallesCombo
{
    public int IdDetalle { get; set; }

    public int IdCombo { get; set; }

    public int IdConsumible { get; set; }

    public int? Cantidad { get; set; }

    public int? PreUnitario { get; set; }

    public virtual Combo IdComboNavigation { get; set; }

    public virtual Consumible IdConsumibleNavigation { get; set; }
}