// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class DetallesFactura
{
    public int IdDetalle { get; set; }

    public int IdFactura { get; set; }

    public double? Precio { get; set; }

    public int? IdConsumible { get; set; }

    public int? IdCombo { get; set; }

    public int? IdEntrada { get; set; }

    public int? IdPromocion { get; set; }

    public virtual Combo IdComboNavigation { get; set; }

    public virtual Consumible IdConsumibleNavigation { get; set; }

    public virtual Entrada IdEntradaNavigation { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}