// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Entrada
{
    public int IdEntrada { get; set; }

    public int IdFuncion { get; set; }

    public int IdButaca { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}