// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public int IdCliente { get; set; }

    public int IdEmpleado { get; set; }

    public DateTime? Fecha { get; set; }

    public int IdMedioPago { get; set; }

    public int IdEstadoCompra { get; set; }

    public int IdFormaCompra { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual EstadosCompra IdEstadoCompraNavigation { get; set; }

    public virtual FormaCompra IdFormaCompraNavigation { get; set; }

    public virtual MediosPago IdMedioPagoNavigation { get; set; }
}