// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class FormaCompra
{
    public int IdFormaCompra { get; set; }

    public string FormaCompra1 { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}