// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string NomPelicula { get; set; }

    public int IdGenero { get; set; }

    public int IdClasificacion { get; set; }

    public int IdEstadoPeli { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual Clasificacion IdClasificacionNavigation { get; set; }

    public virtual EstadoPelicula IdEstadoPeliNavigation { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }
}