// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public string Descripcion { get; set; }

    public DateOnly? VigenciaDesde { get; set; }

    public DateOnly? VigenciaHasta { get; set; }

    public decimal? ValorDescuento { get; set; }

    public bool? Activo { get; set; }

    public int IdTipoPromo { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual TiposPromocion IdTipoPromoNavigation { get; set; }

    public virtual ICollection<PromocionesCondicione> PromocionesCondiciones { get; set; } = new List<PromocionesCondicione>();

    public virtual ICollection<PromocionesEntrada> PromocionesEntrada { get; set; } = new List<PromocionesEntrada>();
}