// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class PromocionesCondicione
{
    public int IdPromoCond { get; set; }

    public int IdPromocion { get; set; }

    public int IdCondicion { get; set; }

    public virtual Condicione IdCondicionNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}