// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class SalaButaca
{
    public int IdSalaButacas { get; set; }

    public int IdButaca { get; set; }

    public int IdSala { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }
}