// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public string NomSala { get; set; }

    public int? CantButacas { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<SalaButaca> SalaButacas { get; set; } = new List<SalaButaca>();
}