// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class TiposProyeccion
{
    public int IdTipoProyeccion { get; set; }

    public string TipoProyeccion { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<PromocionesEntrada> PromocionesEntrada { get; set; } = new List<PromocionesEntrada>();
}