// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class TiposCliente
{
    public int IdTipoCliente { get; set; }

    public string TipoCliente { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}